-- Although the mysql tool will generate labels for the columns returned by your queries,
-- you may want to assign your own labels.

-- While you might want to assign a new label to
-- a column from a table (if it is poorly or ambiguously named), you will almost certainly
-- want to assign your own labels to those columns in your result set that are generated by
-- expressions or built-in function calls.

 -- You can do so by adding a column alias after each element of your select clause.
 SELECT
    language_id,
    'COMMON' language_usage,
    language_id * 3.1415927 lang_pi_value,
    upper(name) language_name
FROM language;

-- +-------------+----------------+---------------+---------------+ 
-- | language_id | language_usage | lang_pi_value | language_name | 
-- +-------------+----------------+---------------+---------------+ 
-- |           1 | COMMON         |     3.1415927 | ENGLISH       | 
-- |           2 | COMMON         |     6.2831854 | ITALIAN       | 
-- |           3 | COMMON         |     9.4247781 | JAPANESE      | 
-- |           4 | COMMON         |    12.5663708 | MANDARIN      | 
-- |           5 | COMMON         |    15.7079635 | FRENCH        | 
-- |           6 | COMMON         |    18.8495562 | GERMAN        | 
-- +-------------+----------------+---------------+---------------+ 

-- In order to make your column aliases stand out even more, you also have the option
-- of using the `as` keyword before the alias name, as in:
SELECT
    language_id,
     'COMMON' AS language_usage,
     language_id * 3.1415927 AS lang_pi_value,
     upper(name) AS language_name 
FROM language;